### ISSUE TITLE
Dessin des courbes

### ISSUE THREAD

**Issue by Anonymous-computer** [hippotese/datafficheur#6]
Au niveau du dessin des courbes :

Les couleurs sont un peu pastel, pourrait-on avoir des couleurs plus vives et plus contrastées ? 

Ou la possibilité de les changer dans un fichier py de configuration ?

**Comment by Anonymous-computer** [comment]
Bonjour.

Les couleurs sont "pastel" car j'ai ajouté de la transparence ([plotting.py#L30C36-L30C45](https://github.com/hippotese/datafficheur/blob/2fbd867ba5a6b5c11ebd4c21ad59530cb12098ca/plotting.py#L30C36-L30C45)) pour que la superposition des courbes ne cache pas de l'information. 

Nous pourrions en effet ajouter un fichier de configuration _(py, ini, yml, toml, ou autre)_ ou ajouter cela dans le fichier [constants.py](https://github.com/hippotese/datafficheur/blob/main/constants.py).

**Comment by Hippotese-Deny-Fady** [comment]
Testé, Ok pour moi.
